global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9253']

  - job_name: 'backup-metrics'
    static_configs:
      - targets: ['backup-metrics-exporter:9100']
